#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

$(which k3s) \
server \
--write-kubeconfig=/k3s-config/kube-config.yaml \
--data-dir=/data \
--disable=traefik,servicelb,metrics-server,local-storage \
--disable-network-policy \
--disable-agent \
--disable-scheduler \
--disable-cloud-controller \
--flannel-backend=none \
--kube-controller-manager-arg=controllers=*,-nodeipam,-nodelifecycle,-persistentvolume-binder,-attachdetach,-persistentvolume-expander,-cloud-node-lifecycle
