"specs":
  - "crd": "https://doc.crds.dev/raw/github.com/crossplane/crossplane@v1.2.1"
    "localName": "crossplane"
    "openapi": "http://localhost:8001/openapi/v2"
    "output": "crossplane/crossplane/1.2"
    "prefix": "^io\\.crossplane\\.(pkg|apiextensions)\\..*"
    "repository": "github.com/jsonnet-libs/crossplane-lib"
  - "crd": "https://doc.crds.dev/raw/github.com/crossplane/provider-aws@v0.18.1"
    "localName": "crossplane_aws"
    "openapi": "http://localhost:8001/openapi/v2"
    "output": "crossplane/provider-aws/0.18"
    "prefix": "^io\\.crossplane\\.aws\\..*"
    "repository": "github.com/jsonnet-libs/crossplane-lib"
  - "crd": "https://doc.crds.dev/raw/github.com/crossplane/provider-gcp@v0.17.0"
    "localName": "crossplane_gcp"
    "openapi": "http://localhost:8001/openapi/v2"
    "output": "crossplane/provider-gcp/0.17"
    "prefix": "^io\\.crossplane\\.gcp\\..*"
    "repository": "github.com/jsonnet-libs/crossplane-lib"
  - "crd": "https://doc.crds.dev/raw/github.com/crossplane/provider-azure@v0.16.1"
    "localName": "crossplane_azure"
    "openapi": "http://localhost:8001/openapi/v2"
    "output": "crossplane/provider-azure/0.16"
    "prefix": "^io\\.crossplane\\.azure\\..*"
    "repository": "github.com/jsonnet-libs/crossplane-lib"
  - "crd": "https://raw.githubusercontent.com/istio/istio/1.8.1/manifests/charts/base/crds/crd-all.gen.yaml"
    "localName": "istio"
    "openapi": "http://localhost:8001/openapi/v2"
    "output": "istio/1.8"
    "prefix": "^io\\.istio\\..*"
    "repository": "github.com/jsonnet-libs/istio-lib"
  - "crd": "https://raw.githubusercontent.com/GoogleCloudPlatform/k8s-config-connector/1.33.0/install-bundles/install-bundle-workload-identity/crds.yaml"
    "localName": "cnrm"
    "openapi": "http://localhost:8001/openapi/v2"
    "output": "cnrm/1.33"
    "prefix": "^com\\.google\\.cloud\\.cnrm\\..*"
    "repository": "github.com/jsonnet-libs/cnrm-lib"
