#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

DATADIR=$(mktemp -d)

$(which k3s) \
server \
--write-kubeconfig="${KUBECONFIG}" \
--data-dir="${DATADIR}" \
--disable=traefik,servicelb,metrics-server,local-storage \
--disable-network-policy \
--disable-agent \
--disable-scheduler \
--disable-cloud-controller \
--flannel-backend=none \
--kube-controller-manager-arg=controllers=*,-nodeipam,-nodelifecycle,-persistentvolume-binder,-attachdetach,-persistentvolume-expander,-cloud-node-lifecycle
